version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: blogdb
      POSTGRES_USER: bloguser
      POSTGRES_PASSWORD: blogpass
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped

  web:
    build: .
    env_file: .env
    depends_on: [db]
    ports:
      - "80:8000"
    restart: unless-stopped

volumes:
  pg_data:
  static_volume: