name: Build & Deploy to K8s

on:
  push:
    branches: ["main"]

env:
  REGISTRY_ID: crpagrrnlkadtf6n9au1
  IMAGE_NAME: mini-blog
  NAMESPACE: mini-blog
  DEPLOYMENT: mini-blog

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check secrets presence
        run: |
          [ -n "${{ secrets.YC_SA_KEY_JSON_B64 }}" ] || { echo "❌ YC_SA_KEY_JSON_B64 is empty"; exit 1; }
          [ -n "${{ secrets.KUBECONFIG_BASE64 }}" ] || { echo "❌ KUBECONFIG_BASE64 is empty"; exit 1; }

      - name: Restore SA key from base64
        run: |
          echo "${{ secrets.YC_SA_KEY_JSON_B64 }}" | base64 -d > sa-key.json
          jq -e . sa-key.json >/dev/null 2>&1 || { echo "❌ sa-key.json invalid JSON"; exit 1; }

      - name: Install yc CLI
        run: |
          curl -sSL https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash
          echo "${HOME}/yandex-cloud/bin" >> $GITHUB_PATH

      - name: Auth with SA key and get IAM token
        id: iam
        run: |
          yc config set service-account-key sa-key.json
          IAM_TOKEN=$(yc iam create-token)
          [ -n "$IAM_TOKEN" ] || { echo "❌ Failed to obtain IAM token"; exit 1; }
          echo "IAM_TOKEN=${IAM_TOKEN}" >> $GITHUB_OUTPUT

      - name: Docker login to Yandex CR
        run: |
          echo "${{ steps.iam.outputs.IAM_TOKEN }}" | docker login cr.yandex -u iam --password-stdin

      - name: Build & Push image
        working-directory: blog_project
        run: |
          IMAGE="cr.yandex/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          # (опционально) тег latest:
          # docker tag "$IMAGE" "cr.yandex/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:latest"
          # docker push "cr.yandex/${{ env.REGISTRY_ID }}/${{ env.IMAGE_NAME }}:latest"

      - name: Rollout on VM via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -e
            IMAGE="cr.yandex/crpagrrnlkadtf6n9au1/mini-blog:${{ github.sha }}"
            kubectl -n mini-blog set image deploy/mini-blog mini-blog="$IMAGE"
            kubectl -n mini-blog rollout status deploy/mini-blog

      - name: Configure kubectl
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 -d > ~/.kube/config
          kubectl version --client
          kubectl cluster-info

      - name: Set image & rollout
        run: |
          kubectl -n "${{ env.NAMESPACE }}" set image deploy/${{ env.DEPLOYMENT }} ${{ env.DEPLOYMENT }}="${IMAGE}"
          kubectl -n "${{ env.NAMESPACE }}" rollout status deploy/${{ env.DEPLOYMENT }}"