name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: testuser       # имя пользователя
          POSTGRES_PASSWORD: testpass   # пароль
          POSTGRES_DB: test_db          # имя базы
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      working-directory: ${{ github.workspace }}/blog_project
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run migrations
      working-directory: ${{ github.workspace }}/blog_project
      env:
        POSTGRES_USER: testuser
        POSTGRES_PASSWORD: testpass
        POSTGRES_DB: test_db
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        DATABASE_URL: postgres://testuser:testpass@localhost:5432/test_db
      run: python manage.py migrate

    - name: Run tests
      working-directory: ${{ github.workspace }}/blog_project
      env:
        POSTGRES_USER: testuser
        POSTGRES_PASSWORD: testpass
        POSTGRES_DB: test_db
        POSTGRES_HOST: localhost
        POSTGRES_PORT: 5432
        DATABASE_URL: postgres://testuser:testpass@localhost:5432/test_db
      run: python manage.py test